"""Rendering — a colourful terminal report, live progress, markdown + PDF export."""
from __future__ import annotations

from datetime import datetime, timezone

from rich.console import Console, Group
from rich.panel import Panel
from rich.text import Text

from .checks import ScanResult

# brand chrome = blues + purples; severities keep their conventional colours
PURPLE = "#a855f7"
BLUE = "#38bdf8"
SEV_STYLE = {"high": "bold #f87171", "medium": "bold #fbbf24",
             "low": "#38bdf8", "info": "#94a3b8"}
SEV_LABEL = {"high": "HIGH", "medium": "MED", "low": "LOW", "info": "INFO"}
CAT_ICON = {"transport": "🔒", "headers": "📋", "cookies": "🍪",
            "disclosure": "📢", "exposure": "📂", "methods": "🔧"}


def _summary_bar(result: ScanResult) -> Text:
    counts = result.by_severity
    t = Text()
    for sev in ("high", "medium", "low", "info"):
        n = counts.get(sev, 0)
        t.append(f" {SEV_LABEL[sev]} {n} ", style=f"{SEV_STYLE[sev]} reverse" if n else "dim")
        t.append(" ")
    return t


def make_progress_reporter(console: Console):
    """Return an `on_event` callback for `checks.scan` that prints live, colourful
    per-check progress — what's running, and each finding as it surfaces."""
    def on_event(kind: str, **k) -> None:
        if kind == "step":
            icon = CAT_ICON.get(k.get("category"), "•")
            console.print(Text.assemble(
                ("  ▸ ", f"bold {BLUE}"),
                (f"{icon} {k['name']}", "bold white"),
                (f"   {k['desc']}", "dim")))
        elif kind == "finding":
            f = k["finding"]
            colour = SEV_STYLE[f.severity].split()[-1]
            console.print(Text.assemble(
                ("       ", ""),
                (f" {SEV_LABEL[f.severity]} ", f"{SEV_STYLE[f.severity]} reverse"),
                ("  ", ""), (f.title, colour)))
        elif kind == "clean":
            console.print(Text.assemble(("       ✓ ", "bold #4ade80"), ("clean", "#4ade80")))
        elif kind == "unreachable":
            console.print(Text.assemble(("  ✗ ", "bold #f87171"),
                          (f"could not reach {k['url']} — {k['error']}", "#f87171")))
    return on_event


def render(result: ScanResult, console: Console) -> None:
    title = Text.assemble(("temple-guard", f"bold {PURPLE}"), ("  ·  self-scan report", f"{BLUE}"))
    if not result.reachable:
        console.print(Panel(f"[bold #f87171]Could not reach[/] {result.url}\n[dim]{result.error}[/]",
                            title=title, border_style="#f87171"))
        return

    header = Group(
        Text.assemble(("Target  ", "dim"), (result.url, f"bold {BLUE}")),
        Text.assemble(("Status  ", "dim"), (str(result.status), "white"),
                      ("    Server  ", "dim"), (result.server or "—", "white")),
        Text.assemble(("Result  ", "dim"), (f"{len(result.findings)} findings   ", "white"), _summary_bar(result)),
    )
    console.print(Panel(header, title=title, border_style=PURPLE, padding=(1, 2)))

    if not result.findings:
        console.print(Panel("[bold #4ade80]✓ No issues found — nice.[/]", border_style="#4ade80"))
        return

    for f in result.findings:
        icon = CAT_ICON.get(f.category, "•")
        head = Text.assemble((f" {SEV_LABEL[f.severity]} ", f"{SEV_STYLE[f.severity]} reverse"),
                             ("  ", ""), (f"{icon} {f.title}", "bold white"))
        body = Group(
            Text.assemble(("evidence   ", "dim"), (f.evidence, "#cbd5e1")),
            Text.assemble(("remediate  ", f"dim {BLUE}"), (f.remediation, "#e2e8f0")),
        )
        console.print(Panel(body, title=head, title_align="left",
                            border_style=SEV_STYLE[f.severity].split()[-1], padding=(0, 1)))


def to_markdown(result: ScanResult) -> str:
    c = result.by_severity
    lines = [
        f"# temple-guard — self-scan report",
        "",
        f"**Target:** `{result.url}`  ",
        f"**Status:** {result.status}  ·  **Server:** {result.server or '—'}  ",
        f"**Findings:** {len(result.findings)} "
        f"(🔴 {c['high']} high · 🟠 {c['medium']} medium · 🔵 {c['low']} low · ⚪ {c['info']} info)",
        "",
    ]
    if not result.reachable:
        return "\n".join(lines + [f"> Could not reach the target: {result.error}"])
    if not result.findings:
        return "\n".join(lines + ["✓ No issues found."])
    lines += ["| Severity | Finding | Remediation |", "|---|---|---|"]
    emoji = {"high": "🔴 High", "medium": "🟠 Medium", "low": "🔵 Low", "info": "⚪ Info"}
    for f in result.findings:
        rem = f.remediation.replace("|", "\\|")
        ttl = f.title.replace("|", "\\|")
        lines.append(f"| {emoji[f.severity]} | {ttl} | {rem} |")
    lines += ["", "<details><summary>Evidence</summary>", ""]
    for f in result.findings:
        lines.append(f"- **{f.title}** — `{f.evidence}`")
    lines += ["", "</details>", "",
              "_Generated by temple-guard — run only against apps you own or are authorized to test._"]
    return "\n".join(lines)


# --- PDF export -------------------------------------------------------------
_PDF_REPL = {"→": "->", "…": "...", "≥": ">=", "≤": "<=", "•": "-", "·": "-",
             "—": "-", "–": "-", "’": "'", "‘": "'", "“": '"', "”": '"',
             "🔴": "", "🟠": "", "🔵": "", "⚪": "", "✓": ""}


def _pt(s: str) -> str:
    """Down-convert to latin-1 so fpdf2 core fonts render it (no font files needed)."""
    for k, v in _PDF_REPL.items():
        s = s.replace(k, v)
    return s.encode("latin-1", "ignore").decode("latin-1")


def to_pdf(result: ScanResult, path: str) -> None:
    """Render a clean, branded PDF report. Pure-Python (fpdf2) — no browser needed."""
    from fpdf import FPDF  # lazy: only needed when a PDF is requested

    NAVY, PURP, BLU = (11, 17, 32), (168, 85, 247), (56, 189, 248)
    WHITE, DARK, GRAY, LIGHT = (255, 255, 255), (30, 41, 59), (100, 116, 139), (226, 232, 240)
    SEV = {"high": (248, 113, 113), "medium": (251, 191, 36),
           "low": (56, 189, 248), "info": (148, 163, 184)}

    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()

    # header band
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, 210, 30, style="F")
    pdf.set_xy(14, 8)
    pdf.set_text_color(*PURP)
    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(0, 9, "TEMPLE GUARD")
    pdf.set_xy(14, 19)
    pdf.set_text_color(*BLU)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 5, "self-scan report")
    pdf.set_xy(pdf.l_margin, 38)

    if not result.reachable:
        pdf.set_text_color(*SEV["high"])
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 7, _pt(f"Could not reach {result.url}\n{result.error}"))
        pdf.output(path)
        return

    # meta
    pdf.set_text_color(*DARK)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 7, _pt(f"Target:  {result.url}"))
    pdf.set_text_color(*GRAY)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 5, _pt(f"Status {result.status}    Server {result.server or '-'}    "
                             f"Generated {datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}"))
    pdf.ln(2)

    # severity summary pills
    c = result.by_severity
    pdf.set_font("Helvetica", "B", 9)
    x, y = pdf.l_margin, pdf.get_y()
    for sev in ("high", "medium", "low", "info"):
        label = f"{SEV_LABEL[sev]} {c.get(sev, 0)}"
        w = pdf.get_string_width(label) + 8
        pdf.set_fill_color(*SEV[sev])
        pdf.set_text_color(*WHITE)
        pdf.set_xy(x, y)
        pdf.cell(w, 7, label, align="C", fill=True)
        x += w + 3
    pdf.set_xy(pdf.l_margin, y + 11)
    pdf.set_draw_color(*LIGHT)
    pdf.line(pdf.l_margin, pdf.get_y(), 210 - pdf.r_margin, pdf.get_y())
    pdf.ln(4)
    pdf.set_x(pdf.l_margin)

    if not result.findings:
        pdf.set_text_color(74, 222, 128)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, "No issues found.")
        pdf.output(path)
        return

    pdf.set_text_color(*DARK)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 8, "Findings & remediation")
    pdf.ln(1)

    for f in result.findings:
        y = pdf.get_y()
        pdf.set_font("Helvetica", "B", 8)
        lbl = SEV_LABEL[f.severity]
        w = pdf.get_string_width(lbl) + 6
        pdf.set_fill_color(*SEV[f.severity])
        pdf.set_text_color(*WHITE)
        pdf.set_xy(pdf.l_margin, y)
        pdf.cell(w, 6, lbl, align="C", fill=True)
        pdf.set_text_color(*DARK)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_xy(pdf.l_margin + w + 3, y)
        pdf.multi_cell(0, 6, _pt(f.title))
        pdf.set_x(pdf.l_margin)
        pdf.set_text_color(*GRAY)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, _pt(f"Evidence:    {f.evidence}"))
        pdf.set_x(pdf.l_margin)
        pdf.set_text_color(*DARK)
        pdf.multi_cell(0, 5, _pt(f"Remediate:  {f.remediation}"))
        pdf.ln(3)

    pdf.set_xy(pdf.l_margin, -14)
    pdf.set_text_color(*GRAY)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, _pt("Generated by temple-guard - run only against apps you own or are authorized to test."),
             align="C")
    pdf.output(path)
