"""Rendering — a colourful terminal remediation report + a markdown export."""
from __future__ import annotations

from rich.console import Console, Group
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from .checks import ScanResult

# brand chrome = blues + purples; severities keep their conventional colours
PURPLE = "#a855f7"
BLUE = "#38bdf8"
SEV_STYLE = {"high": "bold #f87171", "medium": "bold #fbbf24",
             "low": "#38bdf8", "info": "#94a3b8"}
SEV_LABEL = {"high": "HIGH", "medium": "MED", "low": "LOW", "info": "INFO"}
CAT_ICON = {"transport": "🔒", "headers": "📋", "cookies": "🍪",
            "disclosure": "📢", "exposure": "📂", "methods": "🔧"}


def _summary_bar(result: ScanResult) -> Text:
    counts = result.by_severity
    t = Text()
    for sev in ("high", "medium", "low", "info"):
        n = counts.get(sev, 0)
        t.append(f" {SEV_LABEL[sev]} {n} ", style=f"{SEV_STYLE[sev]} reverse" if n else "dim")
        t.append(" ")
    return t


def render(result: ScanResult, console: Console) -> None:
    title = Text.assemble(("temple-guard", f"bold {PURPLE}"), ("  ·  self-scan report", f"{BLUE}"))
    if not result.reachable:
        console.print(Panel(f"[bold #f87171]Could not reach[/] {result.url}\n[dim]{result.error}[/]",
                            title=title, border_style="#f87171"))
        return

    header = Group(
        Text.assemble(("Target  ", "dim"), (result.url, f"bold {BLUE}")),
        Text.assemble(("Status  ", "dim"), (str(result.status), "white"),
                      ("    Server  ", "dim"), (result.server or "—", "white")),
        Text.assemble(("Result  ", "dim"), (f"{len(result.findings)} findings   ", "white"), _summary_bar(result)),
    )
    console.print(Panel(header, title=title, border_style=PURPLE, padding=(1, 2)))

    if not result.findings:
        console.print(Panel("[bold #4ade80]✓ No issues found — nice.[/]", border_style="#4ade80"))
        return

    for f in result.findings:
        icon = CAT_ICON.get(f.category, "•")
        head = Text.assemble((f" {SEV_LABEL[f.severity]} ", f"{SEV_STYLE[f.severity]} reverse"),
                             ("  ", ""), (f"{icon} {f.title}", "bold white"))
        body = Group(
            Text.assemble(("evidence   ", "dim"), (f.evidence, "#cbd5e1")),
            Text.assemble(("remediate  ", f"dim {BLUE}"), (f.remediation, "#e2e8f0")),
        )
        console.print(Panel(body, title=head, title_align="left",
                            border_style=SEV_STYLE[f.severity].split()[-1], padding=(0, 1)))


def to_markdown(result: ScanResult) -> str:
    c = result.by_severity
    lines = [
        f"# temple-guard — self-scan report",
        "",
        f"**Target:** `{result.url}`  ",
        f"**Status:** {result.status}  ·  **Server:** {result.server or '—'}  ",
        f"**Findings:** {len(result.findings)} "
        f"(🔴 {c['high']} high · 🟠 {c['medium']} medium · 🔵 {c['low']} low · ⚪ {c['info']} info)",
        "",
    ]
    if not result.reachable:
        return "\n".join(lines + [f"> Could not reach the target: {result.error}"])
    if not result.findings:
        return "\n".join(lines + ["✓ No issues found."])
    lines += ["| Severity | Finding | Remediation |", "|---|---|---|"]
    emoji = {"high": "🔴 High", "medium": "🟠 Medium", "low": "🔵 Low", "info": "⚪ Info"}
    for f in result.findings:
        rem = f.remediation.replace("|", "\\|")
        ttl = f.title.replace("|", "\\|")
        lines.append(f"| {emoji[f.severity]} | {ttl} | {rem} |")
    lines += ["", "<details><summary>Evidence</summary>", ""]
    for f in result.findings:
        lines.append(f"- **{f.title}** — `{f.evidence}`")
    lines += ["", "</details>", "",
              "_Generated by temple-guard — run only against apps you own or are authorized to test._"]
    return "\n".join(lines)
